### ISSUE TITLE
[DCR]: clicking on "i have written down all 33 words" crashes the app

### ISSUE THREAD

**Issue by dmigwi** [dmigwi/migration#74]
from the wallet name, this seems like a restored wallet, so it shouldn't even be asking to backup, seems like the root cause of the problem, because a restore wallet would have a seed length of 0, either ways this should be investigated

see the crash log below

```
2023-05-26 16:52:38.906 [ERR] UI: Get "/markets/DCR-USDT/ticker": unsupported protocol scheme ""
panic: runtime error: index out of range [-1]

goroutine 39 [running]:
code.cryptopower.dev/group/cryptopower/ui/page/seedbackup.(*VerifySeedPage).getMultiSeed(0xc001efb800, 0xffffffffffffffff, {0xc0078ca000, 0x200, 0x200})
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/ui/page/seedbackup/verify_seed.go:124 +0x86a
code.cryptopower.dev/group/cryptopower/ui/page/seedbackup.(*VerifySeedPage).OnNavigatedTo(0xc001efb800)
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/ui/page/seedbackup/verify_seed.go:102 +0x2f1
code.cryptopower.dev/group/cryptopower/app.(*PageStack).Push(0xc002f12bd0, {0x1dd4c08, 0xc001efb800}, {0x1dd7a40, 0xc002f12c00})
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/app/pagestack.go:67 +0x538
code.cryptopower.dev/group/cryptopower/app.(*SimpleWindowNavigator).Display(0xc002f12c00, {0x1dd4c08?, 0xc001efb800?})
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/app/window.go:49 +0x39
code.cryptopower.dev/group/cryptopower/ui/page/seedbackup.(*SaveSeedPage).HandleUserInteractions(0xc003fe0380)
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/ui/page/seedbackup/save_seed.go:168 +0x8b
code.cryptopower.dev/group/cryptopower/ui.(*Window).handleFrameEvent(0xc000614e60, {{0xc1145355f8b7c807, 0xc3fabb61eb, 0x2cbd5e0}, {0x3f800000, 0x3f800000}, {0x320, 0x258}, {0x0, 0x0, ...}, ...})
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/ui/window.go:223 +0x14c
code.cryptopower.dev/group/cryptopower/ui.(*Window).HandleEvents(0xc000614e60)
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/ui/window.go:196 +0x2b9
main.main.func3()
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/main.go:110 +0x1d
created by main.main
 /home/kennedy/Projects/src/gitlab.com/dreacot/cryptopower/main.go:108 +0x61b
exit status 2
```

*(Issue originally authored by: Kennedy Izuegbu in gitlab.com)*

**Comment by dmigwi** [comment]
changed the description

 *By Kennedy Izuegbu on 2023-05-26T15:59:51 (imported from GitLab)*

*(Comment originally authored by: Kennedy Izuegbu in gitlab.com)*

**Comment by dmigwi** [comment]
assigned to @dmigwi

*(Comment originally authored by: Migwi Ndungu in gitlab.com)*

**Comment by dmigwi** [comment]
Unable to replicate this!

*(Comment originally authored by: Migwi Ndungu in gitlab.com)*
